config/routes.rb
Rails.application.routes.draw do
  resources :testimonials, except: [:show] do
    get 'manage', on: :collection
  end
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :body, :company, :name, :position, :published

  scope :published, where(published: true)
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  include SessionsHelper

  before_filter :is_admin, except: [:index]

  def index
    @testimonials = Testimonial.paginate page: params[:page], per_page: 10
  end
  def new
    @testimonial = Testimonial.new
  end
  def create
    @testimonial = Testimonial.new params[:testimonial]
    if @testimonial.save
      flash[:success] = 'Testimonial Created'
      redirect_to manage_testimonials_path
    else
      render :new
    end
  end
  def edit
    @testimonial = Testimonial.find params[:id]
  end
  def update
    @testimonial = Testimonial.find params[:id]
    if @testimonial.update_attributes params[:testimonial]
      flash[:success] = 'Testimonial Updated'
      redirect_to manage_testimonials_path
    else
      render :edit
    end
  end
  def manage
    @testimonials = Testimonial.all
  end
  def destroy
    Testimonial.destroy params[:id]
    flash[:success] = 'Testimonial destroyed'
    redirect_to manage_testimonials_path
  end

  private
    def is_admin
      redirect_to signin_path, error: "You are not authorized to do this" unless is_admin?
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
  def get_random_testimonial
    Testimonial.published.sample
  end
end

app/views/testimonials/_error_messages.html.haml
- if @testimonial.errors.any?
  %div{id: "error_explanation"}
    .alert.alert-error
      The form contains
      = pluralize(@testimonial.errors.count, "error") + "."
    %ul
      - @testimonial.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/testimonials/_form.html.haml
= form_for @testimonial do |f|
  = render 'error_messages'
  .row-fluid
    .span4
      %p
        = f.label :name
        = f.text_field :name
      %p
        = f.label :company
        = f.text_field :company
      %p
        = f.label :position
        = f.text_field :position
      %p
        = f.label :published
        = f.check_box :published
    .span8
      %p
        = f.label :body
        = f.text_area :body, style: 'width: 100%', rows: '5'
  .row-fluid
    .span12
      = f.submit "#{f.object.new_record? ? 'Create' : 'Update'} Testimonial"
      = link_to 'Cancel', manage_testimonials_path

app/views/testimonials/_manage_testimonial.html.haml
%tr
  %td= manage_testimonial.name
  %td= manage_testimonial.position
  %td= manage_testimonial.company
  %td= manage_testimonial.body
  %td= manage_testimonial.published ? 'Yes' : 'No'
  %td
    = link_to 'Edit', edit_testimonial_path(manage_testimonial), class: 'btn btn-small'
    = link_to 'Delete', manage_testimonial, method: 'delete', data: {confirm: 'You sure?'}, class: 'btn btn-small btn-danger'

app/views/testimonials/_testimonial.html.haml
.testimonial
  .name= testimonial.name
  .position= testimonial.position
  .company= testimonial.company
  .body= testimonial.body

app/views/testimonials/edit.html.haml
%h1 Edit Testimonial
= render 'form'

app/views/testimonials/index.html.haml
%h1 Testimonails
= render @testimonials

app/views/testimonials/manage.html.haml
%h1 Manage Testimonials
%p
  = link_to 'New Testimonial', new_testimonial_path, class: 'btn btn-primary'
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th Name
      %th Position
      %th Company
      %th Body
      %th Published
      %th
  %tbody= render partial: 'manage_testimonial', collection: @testimonials

app/views/testimonials/new.html.haml
%h1 New Testimonial
= render 'form'